<?php
// source: C:\Users\WPJ3Station\DiskGoogle\James\LOCALHOST\DP\Webshooter\app\FrontModule\presenters/templates/Plan/emailPreview.latte

use Latte\Runtime as LR;

class Templateb42be6d8a8 extends Latte\Runtime\Template
{
	public $blocks = [
		'webURI' => 'blockWebURI',
		'emailSubject' => 'blockEmailSubject',
		'emailBody' => 'blockEmailBody',
		'emailYear' => 'blockEmailYear',
	];

	public $blockTypes = [
		'webURI' => 'html',
		'emailSubject' => 'html',
		'emailBody' => 'html',
		'emailYear' => 'html',
	];


	function main()
	{
		extract($this->params);
?>

<?php
		if ($this->getParentName()) return get_defined_vars();
		$this->renderBlock('webURI', get_defined_vars());
?>

<?php
		$this->renderBlock('emailSubject', get_defined_vars());
?>

<?php
		$this->renderBlock('emailBody', get_defined_vars());
?>

<?php
		$this->renderBlock('emailYear', get_defined_vars());
		return get_defined_vars();
	}


	function prepare()
	{
		extract($this->params);
		$this->parentName = '../components/Email/emailLayout.latte';
		Nette\Bridges\ApplicationLatte\UIRuntime::initialize($this, $this->parentName, $this->blocks);
		
	}


	function blockWebURI($_args)
	{
		extract($_args);
		?>   <?php echo LR\Filters::escapeHtmlText($webURI) /* line 6 */ ?>

<?php
	}


	function blockEmailSubject($_args)
	{
		extract($_args);
		?>   <?php echo LR\Filters::escapeHtmlText($subject) /* line 10 */ ?>

<?php
	}


	function blockEmailBody($_args)
	{
		extract($_args);
?>
   <h1 style="font-weight: 900 !important; font-style: normal !important; text-align: center; font-size: 2em;">
      <?php echo LR\Filters::escapeHtmlText($subject) /* line 15 */ ?>

   </h1>

   <p style="margin: 40px 0;">
      Hello, <br><br>
      this is comparision result generated by your plan from Webshooter app.
   </p>

   <h2>
      Plan options:
   </h2>

   <table cellspacing="3" cellpadding="3">
      <tr>
         <td style="width: 200px;">User:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($plan->user->username) /* line 30 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Start date:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText(call_user_func($this->filters->date, $plan->start_date, 'd.m.Y H:i')) /* line 34 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">E-mail:</td>
         <td style="font-weight: bold;">
            <a href="mailto:<?php echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($plan->primary_email)) /* line 39 */ ?>"
               style="font-weight: bold; color:#007fff; text-decoration: underline;"><?php echo LR\Filters::escapeHtmlText($plan->primary_email) /* line 40 */ ?></a>
<?php
		if ($plan->secondary_email) {
			?>               , <a href="mailto:<?php echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($plan->secondary_email)) /* line 42 */ ?>"
                    style="font-weight: bold; color:#007fff; text-decoration: underline;"><?php echo LR\Filters::escapeHtmlText($plan->secondary_email) /* line 43 */ ?></a>
<?php
		}
?>
         </td>
      </tr>
      <tr>
         <td style="width: 200px;">Start options:</td>
         <td style="font-weight: bold;">
<?php
		if ($plan->status == TRUE) {
			?>               <?php echo LR\Filters::escapeHtmlText($plan->start->type) /* line 51 */ ?> –
               every <?php echo LR\Filters::escapeHtmlText($plan->start_value) /* line 52 */ ?>

<?php
			if ($plan->start_type == $daily) {
				?>                  <?php echo LR\Filters::escapeHtmlText($plan->start_value == 1 ? 'day' : 'days') /* line 54 */ ?>

<?php
			}
			elseif ($plan->start_type == $weekly) {
				?>                  <?php echo LR\Filters::escapeHtmlText($plan->start_value == 1 ? 'week' : 'weeks') /* line 56 */ ?>

<?php
			}
			elseif ($plan->start_type == $monthly) {
				?>                  <?php echo LR\Filters::escapeHtmlText($plan->start_value == 1 ? 'month' : 'months') /* line 58 */ ?>

<?php
			}
			elseif ($plan->start_type == $yearly) {
				?>                  <?php echo LR\Filters::escapeHtmlText($plan->start_value == 1 ? 'year' : 'years') /* line 60 */ ?>

<?php
			}
		}
		else {
			?>               <img src="<?php echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($webURI)) /* line 63 */ ?>/images/fa-close.png" alt="Close" style="float: left;">
<?php
		}
?>
         </td>
      </tr>
      <tr>
         <td style="width: 200px;">End options:</td>
         <td style="font-weight: bold;">
<?php
		if ($plan->status == TRUE) {
			if ($plan->end_type == $never) {
				?>                  <?php echo LR\Filters::escapeHtmlText($plan->end->type) /* line 72 */ ?>

<?php
			}
			elseif ($plan->end_type == $occurrence) {
				?>                  After <?php echo LR\Filters::escapeHtmlText($plan->end_occurrence) /* line 74 */ ?> <?php
				echo LR\Filters::escapeHtmlText($plan->end_occurrence == 1 ? 'occurence' : 'occurences') /* line 74 */ ?>

<?php
			}
			elseif ($plan->end_type == $date) {
				?>                  <?php echo LR\Filters::escapeHtmlText(call_user_func($this->filters->date, $plan->end_date, 'd.m.Y H:i')) /* line 76 */ ?>

<?php
			}
		}
		else {
			?>               <img src="<?php echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($webURI)) /* line 79 */ ?>/images/fa-close.png" alt="Close" style="float: left;">
<?php
		}
?>
         </td>
      </tr>
   </table>


   <h2 style="margin-top:40px;">
      Device options:
   </h2>

   <table cellspacing="3" cellpadding="3">
      <tr>
         <td style="width: 200px;">Device type:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($source->device->type->type) /* line 93 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Device:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($source->device->device) /* line 97 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Platform:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($source->device->platform) /* line 101 */ ?></td>
      </tr>
      <tr valign="top">
         <td style="width: 200px;">Screen dimensions:</td>
         <td style="font-weight: bold;">
            <?php echo LR\Filters::escapeHtmlText($source->device->screen_in) /* line 106 */ ?>

            <small>in</small> <?php echo LR\Filters::escapeHtmlText($source->device->screen_width_in) /* line 107 */ ?><small>×</small><?php
		echo LR\Filters::escapeHtmlText($source->device->screen_height_in) /* line 107 */ ?>

            <small>in</small>
            <br>
            <?php echo LR\Filters::escapeHtmlText($source->device->screen_cm) /* line 110 */ ?>

            <small>cm</small>
            <?php echo LR\Filters::escapeHtmlText($source->device->screen_width_cm) /* line 112 */ ?><small>×</small><?php
		echo LR\Filters::escapeHtmlText($source->device->screen_height_cm) /* line 112 */ ?>

            <small>cm</small>
         </td>
      </tr>
      <tr valign="top">
         <td style="width: 200px;">Width × Height:</td>
         <td style="font-weight: bold;">
            <?php echo LR\Filters::escapeHtmlText($source->device->width_px) /* line 119 */ ?><small>×</small><?php
		echo LR\Filters::escapeHtmlText($source->device->height_px) /* line 119 */ ?>

            <small>px</small>
            <br>
            <?php echo LR\Filters::escapeHtmlText($source->device->width_dp) /* line 122 */ ?><small>×</small><?php
		echo LR\Filters::escapeHtmlText($source->device->height_dp) /* line 122 */ ?>

            <small>dp</small>
         </td>
      </tr>
      <tr>
         <td style="width: 200px;">Aspect ratio:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($source->device->aspect_ratio) /* line 128 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Density:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($source->device->density) /* line 132 */ ?></td>
      </tr>
   </table>


   <h2 style="margin-top:40px;">
      Source shoot:
   </h2>

   <a href="<?php
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($webURI)) /* line 141 */;
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($source->path_img)) /* line 141 */ ?>" style="display: block; position: relative; overflow: hidden; height: 400px; border: 1px solid #007fff; border-radius: 0.25rem;">
      <img src="<?php
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($webURI)) /* line 142 */;
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($source->path_img)) /* line 142 */ ?>" alt="Source" style="width: 100%; margin: auto; display: block;">
   </a>

   <table cellspacing="3" cellpadding="3" style="margin-top: 10px;">
      <tr>
         <td style="width: 200px;">URL:</td>
         <td style="font-weight: bold;"><a href="<?php echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($source->url)) /* line 148 */ ?>" style="font-weight: bold; color:#007fff; text-decoration: underline;"><?php
		echo LR\Filters::escapeHtmlText($source->url_autority) /* line 148 */ ?></a></td>
      </tr>
      <tr>
         <td style="width: 200px;">Engine:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText(call_user_func($this->filters->capitalize, $source->engine)) /* line 152 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Browser:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($source->browser_name) /* line 156 */ ?> <?php
		echo LR\Filters::escapeHtmlText($source->browser_version) /* line 156 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Image type:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText(call_user_func($this->filters->upper, $source->img_type)) /* line 160 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Created:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText(call_user_func($this->filters->date, $source->date, 'd.m.Y H:i')) /* line 164 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">User:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($source->user->username) /* line 168 */ ?></td>
      </tr>
   </table>


   <h2 style="margin-top:40px;">
      Target shoot:
   </h2>

   <a href="<?php
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($webURI)) /* line 177 */;
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($target->path_img)) /* line 177 */ ?>" style="display: block; position: relative; overflow: hidden; height: 400px; border: 1px solid #007fff; border-radius: 0.25rem;">
      <img src="<?php
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($webURI)) /* line 178 */;
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($target->path_img)) /* line 178 */ ?>" alt="Target" style="width: 100%; margin: auto; display: block;">
   </a>

   <table cellspacing="3" cellpadding="3" style="margin-top: 10px;">
      <tr>
         <td style="width: 200px;">URL:</td>
         <td style="font-weight: bold;"><a href="<?php echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($target->url)) /* line 184 */ ?>" style="font-weight: bold; color:#007fff; text-decoration: underline;"><?php
		echo LR\Filters::escapeHtmlText($target->url_autority) /* line 184 */ ?></a></td>
      </tr>
      <tr>
         <td style="width: 200px;">Engine:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText(call_user_func($this->filters->capitalize, $target->engine)) /* line 188 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Browser:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($target->browser_name) /* line 192 */ ?> <?php
		echo LR\Filters::escapeHtmlText($target->browser_version) /* line 192 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Image type:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText(call_user_func($this->filters->upper, $target->img_type)) /* line 196 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Created:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText(call_user_func($this->filters->date, $target->date, 'd.m.Y H:i')) /* line 200 */ ?></td>
      </tr>
   </table>


   <h2 style="margin-top:40px;">
      Result:
   </h2>

   <a href="<?php
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($webURI)) /* line 209 */;
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($result->path_img)) /* line 209 */ ?>" style="display: block; position: relative; overflow: hidden; height: 400px; border: 1px solid #007fff; border-radius: 0.25rem;">
      <img src="<?php
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($webURI)) /* line 210 */;
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($result->path_img)) /* line 210 */ ?>" alt="Result" style="width: 100%; margin: auto; display: block;">
   </a>


   <table cellspacing="3" cellpadding="3" style="margin-top: 10px;">
      <tr>
         <td style="width: 200px;">Result color:</td>
         <td style="font-weight: bold;">
            <img src="<?php echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($webURI)) /* line 218 */ ?>/images/fa-image-<?php
		echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($result->color)) /* line 218 */ ?>.png" alt="<?php
		echo LR\Filters::escapeHtmlAttr($result->color) /* line 218 */ ?>" style="float: left;"
                 title="<?php echo LR\Filters::escapeHtmlAttr($result->color) /* line 219 */ ?>">
         </td>
      </tr>
      <tr>
         <td style="width: 200px;">Result background:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($result->background) /* line 224 */ ?></td>
      </tr>
      <tr>
         <td style="width: 200px;">Tolerance:</td>
         <td style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($result->tolerance) /* line 228 */ ?>%</td>
      </tr>
      <tr>
         <td style="width: 200px;">Difference:</td>
         <td style="font-weight: bold;">&le; <?php echo LR\Filters::escapeHtmlText($result->difference) /* line 232 */ ?>%</td>
      </tr>
      <tr>
         <td style="width: 200px;">Result difference:</td>
         <td style="font-weight: bold; font-size: 18px;">
<?php
		if ($result->difference_result <= $result->difference) {
			?>               <i style="color: #ffffff; background: #5cb85c; padding: 1px 5px; border-radius: 0.25rem;"><?php
			echo LR\Filters::escapeHtmlText($result->difference_result) /* line 238 */ ?>

                  %</i>
<?php
		}
		else {
			?>               <i style="color: #ffffff; background: #d9534f; padding: 1px 5px; border-radius: 0.25rem;"><?php
			echo LR\Filters::escapeHtmlText($result->difference_result) /* line 241 */ ?>

                  %</i>
<?php
		}
?>
         </td>
      </tr>
      <tr>
         <td style="width: 200px; vertical-align: top;">Ignore part:</td>
<?php
		if ($result->ignore_active) {
?>
            <td style="font-weight: bold;">
               Top: <span style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($result->ignore_top == null ? 0 : $result->ignore_top) /* line 250 */ ?></span> <small>px</small><br>
               Left: <span style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($result->ignore_left == null ? 0 : $result->ignore_left) /* line 251 */ ?></span> <small>px</small><br>
               Width: <span style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($result->ignore_width == null ? 0 : $result->ignore_width) /* line 252 */ ?></span> <small>px</small><br>
               Height: <span style="font-weight: bold;"><?php echo LR\Filters::escapeHtmlText($result->ignore_height == null ? 0 : $result->ignore_height) /* line 253 */ ?></span> <small>px</small>
            </td>
<?php
		}
		else {
?>
            <td style="font-weight: bold;">
               <img src="<?php echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($webURI)) /* line 257 */ ?>/images/fa-close.png" alt="No">
            </td>
<?php
		}
?>
      </tr>
   </table>
<?php
	}


	function blockEmailYear($_args)
	{
		extract($_args);
		?>   <?php echo LR\Filters::escapeHtmlText(call_user_func($this->filters->date, $year, 'Y')) /* line 265 */ ?>

<?php
	}

}
